-- SINGLE TABLE INHERITANCE (POEAA)
CREATE TABLE Usuarios (
    UUID CHAR(32) PRIMARY KEY,
    Hash TEXT NOT NULL,
    Nombre TEXT NOT NULL,
    Rol VARCHAR(5) NOT NULL CHECK (Rol IN ('admin', 'user', 'owner'))
);

CREATE TABLE Locales (
    UUID CHAR(32) PRIMARY KEY,
    Nombre TEXT NOT NULL,
    Calle TEXT NOT NULL,
    CodigoPostal INTEGER NOT NULL,
    OwnerId CHAR(32) NOT NULL REFERENCES Usuarios(UUID)
);

CREATE TABLE Ofertas (
    UUID CHAR(32) PRIMARY KEY,
    Precio DECIMAL(10,2) NOT NULL,
    Descripcion TEXT NOT NULL,
    Foto BLOB NOT NULL,
    Activa INTEGER NOT NULL CHECK (Activa IN (0, 1)),
    OwnerId CHAR(32) NOT NULL REFERENCES Usuarios(UUID),
    LocalId CHAR(32) NOT NULL REFERENCES Locales(UUID)
);

CREATE TABLE Reservas (
    UUID CHAR(32) PRIMARY KEY,
    Telefono INTEGER,
    Hora TIME NOT NULL,
    Dia DATE NOT NULL,
    UserId CHAR(32) NOT NULL REFERENCES Usuarios(UUID),
    OfertaId CHAR(32) NOT NULL REFERENCES Ofertas(UUID)
);

CREATE TABLE Chats (
    UUID CHAR(32) PRIMARY KEY,
    UserId CHAR(32) NOT NULL REFERENCES Usuarios(UUID),
    OwnerId CHAR(32) NOT NULL REFERENCES Usuarios(UUID),
    IdReserva CHAR(32) NOT NULL REFERENCES Reservas(UUID)
);

CREATE TABLE Mensajes (
    UUID CHAR(32) PRIMARY KEY,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Texto TEXT NOT NULL,
    SenderId CHAR(32) NOT NULL REFERENCES Usuarios(UUID),
    ChatId CHAR(32) NOT NULL REFERENCES Chats(UUID)
);

CREATE TABLE Resennas (
    UUID CHAR(32) PRIMARY KEY,
    Descripcion TEXT NOT NULL,
    UserId CHAR(32) NOT NULL REFERENCES Usuarios(UUID),
    OfertaId CHAR(32) NOT NULL REFERENCES Ofertas(UUID)
);
